# -*- coding: utf-8 -*-
"""Maior entre 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cAiSJdW9SDXyGaZner2xuZn3Zxps5NHK
"""

n1 = float(input("Insira o primeiro numero:"))
n2 = float(input("Insira o segundo numero:"))
n3 = float(input("Insira o terceiro numero:"))

if n1 > n2 and n1 > n3:
    print("O maior numero:", n1)
elif n2 > n1 and n2 > n3:
    print("O maior numero:", n2)
else:
    print("O maior numero:", n3)

